name: yolov13
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - aiofiles==23.2.1
    - albucore==0.0.23
    - albumentations==2.0.4
    - annotated-doc==0.0.4
    - annotated-types==0.7.0
    - anyio==4.12.0
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - click==8.3.1
    - coloredlogs==15.0.1
    - contourpy==1.3.3
    - cycler==0.12.1
    - defusedxml==0.7.1
    - einops==0.8.1
    - fastapi==0.124.2
    - ffmpy==1.0.0
    - filelock==3.20.0
    - flash-attn==2.7.3
    - flatbuffers==25.9.23
    - fonttools==4.61.0
    - fsspec==2025.12.0
    - gradio==4.44.1
    - gradio-client==1.3.0
    - h11==0.16.0
    - httpcore==1.0.9
    - httptools==0.7.1
    - httpx==0.28.1
    - huggingface-hub==0.23.2
    - humanfriendly==10.0
    - idna==3.11
    - importlib-resources==6.5.2
    - jinja2==3.1.6
    - kiwisolver==1.4.9
    - markdown-it-py==4.0.0
    - markupsafe==2.1.5
    - matplotlib==3.10.8
    - mdurl==0.1.2
    - mpmath==1.3.0
    - networkx==3.6.1
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu12==12.1.105
    - onnx==1.14.0
    - onnxruntime==1.15.1
    - onnxruntime-gpu==1.18.0
    - onnxslim==0.1.31
    - opencv-python-headless==4.9.0.80
    - orjson==3.11.5
    - packaging==25.0
    - pandas==2.3.3
    - pillow==10.4.0
    - protobuf==6.33.2
    - psutil==5.9.8
    - py-cpuinfo==9.0.0
    - pycocotools==2.0.7
    - pydantic==2.12.5
    - pydantic-core==2.41.5
    - pydub==0.25.1
    - pygments==2.19.2
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - python-multipart==0.0.20
    - pytz==2025.2
    - pyyaml==6.0.1
    - requests==2.32.5
    - rich==14.2.0
    - ruff==0.14.8
    - safetensors==0.4.3
    - scipy==1.13.0
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - shellingham==1.5.4
    - simsimd==6.5.3
    - six==1.17.0
    - starlette==0.50.0
    - stringzilla==4.4.0
    - supervision==0.22.0
    - sympy==1.14.0
    - timm==1.0.14
    - tomlkit==0.12.0
    - torch==2.2.2
    - torchvision==0.17.2
    - tqdm==4.67.1
    - triton==2.2.0
    - typer==0.20.0
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - ultralytics==8.3.63
    - ultralytics-thop==2.0.18
    - urllib3==2.6.1
    - uvicorn==0.38.0
    - uvloop==0.22.1
    - watchfiles==1.1.1
    - websockets==12.0
prefix: /opt/miniconda3/envs/yolov13
